### PR TITLE
Add a form for creating a journal entry to the div[data-view=entry-form]

### PR DESCRIPTION
**Pull request by Johnny-Baltazar**
task list 2

### CODE REVIEW

**Comment by Johnny-Baltazar** [comment]
nice on desktop and mobile

**Comment by Johnny-Baltazar** [comment]
required inputs

**Comment by Johnny-Baltazar** [comment]
listen for input

**Comment by Johnny-Baltazar** [comment]
listen for submit events

**Comment by Johnny-Baltazar** [comment]
new entries saved

**Comment by Johnny-Baltazar** [comment]
create entry desktop demo

**Comment by Johnny-Baltazar** [comment]
create entry mobile demo

**Comment by Johnny-Baltazar** [comment]
updated issue one

**Review by Zhiwutian — APPROVED** [review]
👍🏼

**Pull request merged**
